# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-03-10 13:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('axf', '0005_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='token',
            field=models.CharField(default='0', max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='arr',
            field=models.CharField(default='0', max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(default='0', max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='0', max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='tel',
            field=models.CharField(default='0', max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(default='0', max_length=100),
        ),
    ]
