# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-03-10 13:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('axf', '0006_auto_20190310_1335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(default='0', max_length=100, unique=True),
        ),
    ]
